In [1]:
import numpy as np
import pandas as pd
import os
import datetime as dt
import time
from copy import deepcopy
import matplotlib.pyplot as plt

from f1_elo.pvp.general import build_pvp_results
from f1_elo.pvp_model.dataset import get_model_ready_pvp_results
from f1_elo.season import calc_season_drivers

import warnings
warnings.filterwarnings("ignore")

In [2]:
from f1_elo.pvp.fetch import get_results_data
from f1_elo.pvp.calc import (
    calc_pvp_results,
    filter_results,
)

from f1_elo.fetch_pvp import read_season_drivers

In [3]:
build_pvp_results()
calc_season_drivers()

In [4]:
results = get_results_data()
results['tournament'] = 'F1'
results = filter_results(results=results)
# results = results.rename(columns={'date': 'game_date', 'year': 'season'})
results['season'] = results['season'].astype(str)

In [5]:
season_drivers = read_season_drivers()
season_drivers = season_drivers.rename(columns={'team': 'driver'})
results = results.merge(season_drivers, how='inner', on=['tournament', 'season', 'driver'])
results = results.sort_values(['season', 'round', 'position'], ascending=True)
results['position'] = 1
results['position'] = results.groupby(['season', 'round'])['position'].cumsum()

In [6]:
results.tail(60)

,resultId,season,round,game_date,circuit,circuit_country,raceId,positionOrder,position,driver,constructor,points,grid,tournament
15056,26689,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,5,5,Charles Leclerc,Ferrari,10.0,6,F1
15057,26690,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,6,6,Lando Norris,McLaren,8.0,1,F1
15058,26691,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,7,7,Yuki Tsunoda,RB F1 Team,6.0,3,F1
15059,26692,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,8,8,Oscar Piastri,McLaren,4.0,8,F1
15060,26693,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,9,9,Liam Lawson,RB F1 Team,2.0,5,F1
15061,26694,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,10,10,Lewis Hamilton,Mercedes,1.0,14,F1
15062,26695,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,11,11,Sergio Pérez,Red Bull,0.0,12,F1
15063,26696,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,12,12,Oliver Bearman,Haas F1 Team,0.0,15,F1
15064,26697,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,13,13,Valtteri Bottas,Sauber,0.0,11,F1
15065,26698,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,14,14,Fernando Alonso,Aston Martin,0.0,9,F1
15066,26699,2024,21,2024-11-03,Autódromo José Carlos Pace,Brazil,1141,15,15,Guanyu Zhou,Sauber,0.0,19,F1
15067,26705,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,1,1,George Russell,Mercedes,25.0,1,F1
15068,26706,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,2,2,Lewis Hamilton,Mercedes,18.0,10,F1
15069,26707,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,3,3,Carlos Sainz,Ferrari,15.0,2,F1
15070,26708,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,4,4,Charles Leclerc,Ferrari,12.0,4,F1
15071,26709,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,5,5,Max Verstappen,Red Bull,10.0,5,F1
15072,26710,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,6,6,Lando Norris,McLaren,9.0,6,F1
15073,26711,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,7,7,Oscar Piastri,McLaren,6.0,8,F1
15074,26712,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,8,8,Nico Hülkenberg,Haas F1 Team,4.0,9,F1
15075,26713,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,9,9,Yuki Tsunoda,RB F1 Team,2.0,7,F1
15076,26714,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,10,10,Sergio Pérez,Red Bull,1.0,15,F1
15077,26715,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,11,11,Fernando Alonso,Aston Martin,0.0,16,F1
15078,26716,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,12,12,Kevin Magnussen,Haas F1 Team,0.0,12,F1
15079,26717,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,13,13,Guanyu Zhou,Sauber,0.0,13,F1
15080,26718,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,14,14,Franco Colapinto,Williams,0.0,0,F1
15081,26719,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,15,15,Lance Stroll,Aston Martin,0.0,18,F1
15082,26720,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,16,16,Liam Lawson,RB F1 Team,0.0,14,F1
15083,26721,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,17,17,Esteban Ocon,Alpine F1 Team,0.0,11,F1
15084,26722,2024,22,2024-11-23,Las Vegas Strip Street Circuit,United States,1142,18,18,Valtteri Bottas,Sauber,0.0,19,F1
15085,26725,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,1,1,Max Verstappen,Red Bull,25.0,2,F1
15086,26726,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,2,2,Charles Leclerc,Ferrari,18.0,5,F1
15087,26727,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,3,3,Oscar Piastri,McLaren,15.0,4,F1
15088,26728,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,4,4,George Russell,Mercedes,12.0,1,F1
15089,26729,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,5,5,Pierre Gasly,Alpine F1 Team,10.0,11,F1
15090,26730,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,6,6,Carlos Sainz,Ferrari,8.0,7,F1
15091,26731,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,7,7,Fernando Alonso,Aston Martin,6.0,8,F1
15092,26732,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,8,8,Guanyu Zhou,Sauber,4.0,12,F1
15093,26733,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,9,9,Kevin Magnussen,Haas F1 Team,2.0,10,F1
15094,26734,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,10,10,Lando Norris,McLaren,2.0,3,F1
15095,26735,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,11,11,Valtteri Bottas,Sauber,0.0,13,F1
15096,26736,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,12,12,Lewis Hamilton,Mercedes,0.0,6,F1
15097,26737,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,13,13,Yuki Tsunoda,RB F1 Team,0.0,14,F1
15098,26738,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,14,14,Liam Lawson,RB F1 Team,0.0,17,F1
15099,26739,2024,23,2024-12-01,Losail International Circuit,Qatar,1143,15,15,Alexander Albon,Williams,0.0,16,F1
15100,26745,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,1,1,Lando Norris,McLaren,25.0,1,F1
15101,26746,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,2,2,Carlos Sainz,Ferrari,18.0,3,F1
15102,26747,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,3,3,Charles Leclerc,Ferrari,15.0,19,F1
15103,26748,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,4,4,Lewis Hamilton,Mercedes,12.0,16,F1
15104,26749,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,5,5,George Russell,Mercedes,10.0,6,F1
15105,26750,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,6,6,Max Verstappen,Red Bull,8.0,4,F1
15106,26751,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,7,7,Pierre Gasly,Alpine F1 Team,6.0,5,F1
15107,26752,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,8,8,Nico Hülkenberg,Haas F1 Team,4.0,7,F1
15108,26753,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,9,9,Fernando Alonso,Aston Martin,2.0,8,F1
15109,26754,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,10,10,Oscar Piastri,McLaren,1.0,2,F1
15110,26755,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,11,11,Alexander Albon,Williams,0.0,18,F1
15111,26756,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,12,12,Yuki Tsunoda,RB F1 Team,0.0,11,F1
15112,26757,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,13,13,Guanyu Zhou,Sauber,0.0,15,F1
15113,26758,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,14,14,Lance Stroll,Aston Martin,0.0,13,F1
15114,26760,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,16,15,Kevin Magnussen,Haas F1 Team,0.0,14,F1
15115,26761,2024,24,2024-12-08,Yas Marina Circuit,UAE,1144,17,16,Liam Lawson,RB F1 Team,0.0,12,F1

In [7]:
from copy import deepcopy
from datetime import date

from numpy import log as np_log
from pandas import (
    DataFrame,
    concat,
)

from f1_elo.constants import RESULT_RATIOS
from f1_elo.fetch_pvp import read_season_drivers


class EnduranceEloCalculation:
    """
    Class represents elo rating calculation logic.
    """
    def __init__(
        self,
        elo_game_value=20,
        new_agent_alpha=1.68,
        calibrated_rating=2000,
        num_calibrated_drivers=20,
        default_rating=1830.9,        
        saturation_rounds=10,
    ):
        """
        Initializes an instance with paths to data files and Elo configuration parameters.

        Arguments:
            elo_game_value (float): default Elo adjustment factor.
            new_agent_alpha (float): coefficient controlling the new agent adjustment.
            calibrated_rating (float): target mean rating for top drivers.
            num_calibrated_drivers (int): number of top drivers to use for calibration.
            default_rating (float): default Elo rating for new drivers.
            saturation_rounds (int): rounds required to reach rating stability.
        """
        self.elo_game_value = elo_game_value
        self.calibrated_rating = calibrated_rating
        self.num_calibrated_drivers = num_calibrated_drivers
        self.default_rating = default_rating
        self.saturation_rounds = saturation_rounds
        self.new_agent_alpha = new_agent_alpha

        self.season_drivers = read_season_drivers()
        self.drivers_years_active = self.season_drivers.groupby(['team']).agg(
            first_season=('season', 'min'),
            last_season=('season', 'max'),
        ).reset_index()

        self.elo_ratings_dict = {}
        self.num_games_per_team = {}

        self.temp_ratings = []
        self.total_rating = None
        self.output = []

    @property
    def log_loss(self):
        """
        Compute the mean log loss across all processed games.

        Returns:
            mean log loss if available as a float, otherwise None.
        """
        if len(self.output) == 0:
            return None
            
        output_df = pd.concat(self.output)
        log_loss = output_df['log_loss'].mean()

        return log_loss

    def reset_log_loss(self):
        """
        Reset stored log loss output.
        """
        self.output = []

    def run_pipeline(self, results):
        """
        Run ratings for every season bases on race results.

        Arguments:
            results (pandas.DataFrame): dataset with PVP interactions history.
        """
        seasons = sorted(results['season'].unique())

        for season in seasons:
            include_ix = self.drivers_years_active['first_season'] == season
            teams_to_include = self.drivers_years_active['team'].loc[include_ix].to_list()
            for team in teams_to_include:
                self.elo_ratings_dict[team] = self.elo_ratings_dict.get(team, self.default_rating)

            self._calibrate_ratings(season=season)

            self.run_season(results=results, season=season)
            exclude_ix = (self.drivers_years_active['last_season'] == season) & (season != '2024')
            teams_to_exclude = self.drivers_years_active['team'].loc[exclude_ix].to_list()
            for team in teams_to_exclude:
                _ = self.elo_ratings_dict.pop(team)

        self.total_rating = concat(self.temp_ratings)

    def run_round(self, round_results):
        """
        Run Elo updates for a single race.

        Arguments:
            round_results (pandas.DataFrame): Race results in PVP format.
        """
        # need a copy as expected result should be calculated on a pre race ratings for all race interactions.
        round_elo_rating_dict = deepcopy(self.elo_ratings_dict)
        round_df = round_results.copy(deep=True)

        round_df['elo_rating'] = round_df['driver'].map(self.elo_ratings_dict)
        round_df['weight'] = round_df['elo_rating'].map(lambda x: 10**(-x/400))
        round_df['num_rounds'] = round_df['driver'].map(self.num_games_per_team).fillna(0)
        round_df['new_agent_multiplier'] = round_df['num_rounds'].map(self._calc_new_agent_multiplier)

        while len(round_df) >= 2:
            ee_df = round_df[['driver', 'position', 'weight', 'new_agent_multiplier']]
            ee_df['probability_to_lose'] = ee_df['weight'] / ee_df['weight'].sum()
            num_losers = len(ee_df.loc[ee_df['position'] == ee_df['position'].max()])
            ee_df['is_last'] = ee_df['position'].map(lambda x: 1/num_losers if x == ee_df['position'].max() else 0)
            ee_df['elo_update'] = self.elo_game_value * ee_df['new_agent_multiplier'] * (ee_df['probability_to_lose'] - ee_df['is_last'])
            self.ee_df = ee_df
            
            elo_updates = ee_df.set_index('driver')['elo_update'].to_dict()
            for driver in elo_updates:
                round_elo_rating_dict[driver] = round_elo_rating_dict[driver] + elo_updates[driver]

            self.elo_updates = elo_updates

            round_df = round_df.loc[round_df['position'] != round_df['position'].max()]

        pvp_round_df = calc_pvp_results(round_results)
        pvp_round_df['result_ratio'] = pvp_round_df['result'].map(RESULT_RATIOS)
        pvp_round_df['exp_result'] = pvp_round_df.apply(self.calc_expected_result, axis=1)
        pvp_round_df['log_loss'] = pvp_round_df.apply(self._calc_log_loss, axis=1)
        self.output.append(pvp_round_df)
            
        self.elo_ratings_dict = round_elo_rating_dict

        round_drivers = set(round_results['driver'])
        for driver in round_drivers:
            self.num_games_per_team[driver] = self.num_games_per_team.get(driver, 0) + 1

    def run_season(self, results, season):
        """
        Execute Elo updates for all rounds within a season.

        Arguments:
            results (pandas.DataFrame): Dataset with race history.
            season (str): Season identifier.
        """
        self._log_current_rating(rating_date=date(int(season), 1, 1))
        season_rounds = sorted(results['round'].loc[results['season'] == season].unique())
        for season_round in season_rounds:
            round_results = results.loc[(results['season'] == season) & (results['round'] == season_round)]
            self.run_round(round_results=round_results)
            self._log_current_rating(rating_date=round_results['game_date'].iloc[0])

        self._log_current_rating(rating_date=date(int(season), 12, 31))

    @staticmethod
    def _calc_log_loss(interaction):
        """
        Calculates the log loss value for PVP interaction between two drivers.

        Arguments:
            interaction (dict): PVP interaction between two drivers.

        Returns:
            The elog loss value as a float.
        """
        res_ratio = interaction['result_ratio']
        exp_result = interaction['exp_result']
        log_loss = -res_ratio * np_log(exp_result) - (1 - res_ratio) * np_log(1 - exp_result)

        return log_loss

    def _calc_new_agent_multiplier(self, num_rounds):
        """
        Compute adjustment multiplier for newly introduced drivers.

        Arguments:
            num_rounds (int): Number of rounds a driver has participated in.

        Returns:
            Adjustment multiplier for rating change as a float.
        """
        multiplier = 1 + self.new_agent_alpha * (1 - min(self.saturation_rounds, num_rounds)/self.saturation_rounds)**2

        return multiplier

    def _calibrate_ratings(self, season):
        """
        Adjust all ratings so that the top drivers’ mean matches the calibrated rating.

        Arguments:
            season (str): Season identifier.
        """
        season_teams = self.season_drivers[['team']].loc[self.season_drivers['season'] == season]
        season_teams['rating'] = season_teams['team'].map(self.elo_ratings_dict)
        season_teams = season_teams.sort_values('rating', ascending=False).reset_index(drop=True)
        if len(season_teams) > self.num_calibrated_drivers:
            season_teams = season_teams.iloc[:self.num_calibrated_drivers]

        calibration_delta = self.calibrated_rating - season_teams['rating'].mean()
        for team in self.elo_ratings_dict:
            self.elo_ratings_dict[team] += calibration_delta

    def _log_current_rating(self, rating_date):
        """
        Log current Elo ratings with a specified date.

        Arguments:
            rating_date (datetime.date): Date of logged ratings.
        """
        temp_rating = DataFrame.from_dict(self.elo_ratings_dict, orient='index').reset_index()
        temp_rating = temp_rating.rename(columns={'index': 'team', 0: 'rating'})
        temp_rating['date'] = rating_date
        self.temp_ratings.append(temp_rating)

    def calc_expected_result(self, row):
        elo1 = self.elo_ratings_dict.get(row['home_team'])
        
        elo2 = self.elo_ratings_dict.get(row['away_team'])
        elo_diff = elo1 - elo2

        exp_res = 1 / (10 ** (-elo_diff / 400) + 1)

        return exp_res

In [8]:
obj = EnduranceEloCalculation(elo_game_value=45)

In [9]:
obj.run_pipeline(results=results)

In [10]:
obj.log_loss

0.47834585712183936

In [11]:
from f1_elo.constants import (
    INIT_DATASET_END_DATE,
    TRAIN_DATASET_END_DATE,
    VALIDATION_DATASET_END_DATE,
)
from f1_elo.gradient import AbstractGradientOptimizer

from numpy.random import uniform


class EnduranceEloGradientOptimizer(AbstractGradientOptimizer):
    """Gradient descent optimizer for tuning Elo model parameters."""

    def __init__(self, gradient_delta=0.0001):
        """
        Construct the object.

        Arguments:
            gradient_delta (float): Step size used for gradient perturbation.
        """
        super().__init__(gradient_delta=gradient_delta)
        self.init_settings = None

    def set_model(self):
        """
        Set the Elo model class to be optimized.
        """
        self.model = EnduranceEloCalculation

    def initialize_model_settings(self):
        """
        Initialize Elo model parameters with random starting values.

        Returns:
            Dictionary with initial Elo parameter settings.
        """
        settings = {'elo_game_value': uniform(10, 500), 'default_rating': uniform(1500, 2000),
                    'new_agent_alpha': uniform(0.1, 10)}

        self.init_settings = settings
        print(settings)

        return settings


def split_dataset(df):
    """
    Split a dataset into initialization, training, and validation subsets based on dates.

    Arguments:
        df (pandas.DataFrame): PVP results dataset.

    Returns:
        dict: Dictionary with keys 'init', 'train', and 'validation' containing the respective subsets.
    """
    init_ix = df['game_date'] <= INIT_DATASET_END_DATE
    init_df = df.loc[init_ix]

    train_ix = (df['game_date'] > INIT_DATASET_END_DATE) & (df['game_date'] <= TRAIN_DATASET_END_DATE)
    train_df = df.loc[train_ix]

    validation_ix = (df['game_date'] > TRAIN_DATASET_END_DATE) & (df['game_date'] <= VALIDATION_DATASET_END_DATE)
    validation_df = df.loc[validation_ix]

    datasets = {'init': init_df, 'train': train_df, 'validation': validation_df}

    return datasets

In [12]:
datasets = split_dataset(df=results)

obj = EnduranceEloGradientOptimizer()
output = obj.run(datasets=datasets, num_epochs=50)

{'elo_game_value': 62.70003752940001, 'default_rating': 1573.8907520169992, 'new_agent_alpha': 1.1033114323713464}
Iteration: 1: 0.5612518464995071
Iteration: 2: 0.5572243335547642
Iteration: 3: 0.5522492939508552
Iteration: 4: 0.547513389005317
Iteration: 5: 0.5440645463375042
Iteration: 6: 0.5426155753099048
Iteration: 7: 0.542051972248845
Iteration: 8: 0.5417468537887232
Iteration: 9: 0.5415156357325305
Iteration: 10: 0.5413245667223561
Iteration: 11: 0.5411640604845901
Iteration: 12: 0.5410282643257602
Iteration: 13: 0.5409129370498897
Iteration: 14: 0.5408146723518698
Iteration: 15: 0.5407306975816831
Iteration: 16: 0.540658739443707
Iteration: 17: 0.5405969230220973
Iteration: 18: 0.5405436938916356
Iteration: 19: 0.5404977573126466
Iteration: 20: 0.5404580303142724
Iteration: 21: 0.5404236036190824
Iteration: 22: 0.5403937111598885
Iteration: 23: 0.5403677055083201
Iteration: 24: 0.5403450408405025
Iteration: 25: 0.5403252503585632
Iteration: 26: 0.5403080720935267
Iteration: 27: 0.5402930317727523
Iteration: 28: 0.5402798195168491
Iteration: 29: 0.5402681885284529
Iteration: 30: 0.5402579266852711
Iteration: 31: 0.54024885232867
Iteration: 32: 0.5402408092116427
Iteration: 33: 0.5402336626760008
Iteration: 34: 0.5402272965039966
Iteration: 35: 0.5402216102711201
Iteration: 36: 0.5402165165683628
Iteration: 37: 0.5402119354647362
Iteration: 38: 0.5402078089556757
Iteration: 39: 0.5402040786272235
Iteration: 40: 0.5402007002535252
Iteration: 41: 0.5401976333578326
Iteration: 42: 0.5401948318403912
Iteration: 43: 0.5401922661203222
Iteration: 44: 0.5401899064856666
Iteration: 45: 0.5401877282204323
Iteration: 46: 0.540185709580699
Iteration: 47: 0.5401838287891992
Iteration: 48: 0.5401820742241543
Iteration: 49: 0.540180431554456
Iteration: 50: 0.5401788882462416

In [32]:
obj.optimized_parameters

{'elo_game_value': 47.04352098949928,
 'default_rating': 1833.863245818816,
 'new_agent_alpha': 0.7588477980588197}

In [34]:
output

,iteration,elo_game_value,default_rating,new_agent_alpha,pre_train_log_loss,pre_validation_log_loss,elo_game_value_delta,new_elo_game_value,default_rating_delta,new_default_rating,new_agent_alpha_delta,new_new_agent_alpha,new_train_log_loss,new_validation_log_loss
0,1,62.700038,1573.890752,1.103311,0.563477,0.444364,-0.243733,62.456305,16.771046,1590.661798,-0.006719,1.096593,0.561252,0.443721
1,2,62.456305,1590.661798,1.096593,0.561252,0.443721,-0.489758,61.966547,32.495638,1623.157436,-0.013126,1.083467,0.557224,0.442569
2,3,61.966547,1623.157436,1.083467,0.557224,0.442569,-0.735374,61.231173,45.500778,1668.658214,-0.018677,1.064791,0.552249,0.441204
3,4,61.231173,1668.658214,1.064791,0.552249,0.441204,-0.969022,60.262151,52.947335,1721.605549,-0.022840,1.041951,0.547513,0.440042
4,5,60.262151,1721.605549,1.041951,0.547513,0.440042,-1.155946,59.106205,52.523047,1774.128596,-0.024974,1.016976,0.544065,0.439453
5,6,59.106205,1774.128596,1.016976,0.544065,0.439453,-1.070709,58.035496,33.139030,1807.267626,-0.020906,0.996070,0.542616,0.439392
6,7,58.035496,1807.267626,0.996070,0.542616,0.439392,-0.971101,57.064395,16.473104,1823.740730,-0.017611,0.978459,0.542052,0.439418
7,8,57.064395,1823.740730,0.978459,0.542052,0.439418,-0.874993,56.189402,6.186729,1829.927459,-0.015213,0.963247,0.541747,0.439381
8,9,56.189402,1829.927459,0.963247,0.541747,0.439381,-0.789693,55.399709,2.015888,1831.943347,-0.013525,0.949722,0.541516,0.439310
9,10,55.399709,1831.943347,0.949722,0.541516,0.439310,-0.714535,54.685175,0.590616,1832.533963,-0.012227,0.937494,0.541325,0.439237
10,11,54.685175,1832.533963,0.937494,0.541325,0.439237,-0.647247,54.037928,0.159420,1832.693383,-0.011157,0.926337,0.541164,0.439174
11,12,54.037928,1832.693383,0.926337,0.541164,0.439174,-0.588684,53.449244,0.032840,1832.726223,-0.010241,0.916096,0.541028,0.439124
12,13,53.449244,1832.726223,0.916096,0.541028,0.439124,-0.536581,52.912663,0.008757,1832.734980,-0.009444,0.906651,0.540913,0.439084
13,14,52.912663,1832.734980,0.906651,0.540913,0.439084,-0.490038,52.422625,0.012702,1832.747682,-0.008744,0.897908,0.540815,0.439055
14,15,52.422625,1832.747682,0.897908,0.540815,0.439055,-0.448303,51.974322,0.022254,1832.769937,-0.008123,0.889785,0.540731,0.439033
15,16,51.974322,1832.769937,0.889785,0.540731,0.439033,-0.410754,51.563568,0.031208,1832.801145,-0.007572,0.882213,0.540659,0.439018
16,17,51.563568,1832.801145,0.882213,0.540659,0.439018,-0.376864,51.186704,0.038203,1832.839347,-0.007078,0.875135,0.540597,0.439008
17,18,51.186704,1832.839347,0.875135,0.540597,0.439008,-0.346192,50.840512,0.043227,1832.882574,-0.006636,0.868498,0.540544,0.439002
18,19,50.840512,1832.882574,0.868498,0.540544,0.439002,-0.318359,50.522154,0.046585,1832.929159,-0.006238,0.862261,0.540498,0.439000
19,20,50.522154,1832.929159,0.862261,0.540498,0.439000,-0.293044,50.229110,0.048606,1832.977765,-0.005878,0.856383,0.540458,0.439000
20,21,50.229110,1832.977765,0.856383,0.540458,0.439000,-0.269970,49.959140,0.049576,1833.027340,-0.005551,0.850832,0.540424,0.439003
21,22,49.959140,1833.027340,0.850832,0.540424,0.439003,-0.248898,49.710242,0.049727,1833.077067,-0.005255,0.845577,0.540394,0.439007
22,23,49.710242,1833.077067,0.845577,0.540394,0.439007,-0.229620,49.480622,0.049247,1833.126315,-0.004985,0.840592,0.540368,0.439012
23,24,49.480622,1833.126315,0.840592,0.540368,0.439012,-0.211954,49.268668,0.048285,1833.174600,-0.004738,0.835854,0.540345,0.439019
24,25,49.268668,1833.174600,0.835854,0.540345,0.439019,-0.195689,49.072980,0.053445,1833.228045,-0.004511,0.831343,0.540325,0.439026
25,26,49.072980,1833.228045,0.831343,0.540325,0.439026,-0.179804,48.893176,0.052114,1833.280159,-0.004307,0.827036,0.540308,0.439034
26,27,48.893176,1833.280159,0.827036,0.540308,0.439034,-0.165917,48.727259,0.079866,1833.360025,-0.004114,0.822922,0.540293,0.439043
27,28,48.727259,1833.360025,0.822922,0.540293,0.439043,-0.153387,48.573872,0.058425,1833.418450,-0.003938,0.818984,0.540280,0.439051
28,29,48.573872,1833.418450,0.818984,0.540280,0.439051,-0.141818,48.432054,0.042625,1833.461075,-0.003776,0.815207,0.540268,0.439060
29,30,48.432054,1833.461075,0.815207,0.540268,0.439060,-0.131128,48.300925,0.037249,1833.498324,-0.003627,0.811581,0.540258,0.439068
30,31,48.300925,1833.498324,0.811581,0.540258,0.439068,-0.121249,48.179677,0.034448,1833.532772,-0.003488,0.808093,0.540249,0.439076
31,32,48.179677,1833.532772,0.808093,0.540249,0.439076,-0.112112,48.067564,0.032287,1833.565059,-0.003359,0.804733,0.540241,0.439084
32,33,48.067564,1833.565059,0.804733,0.540241,0.439084,-0.103657,47.963907,0.030302,1833.595362,-0.003240,0.801494,0.540234,0.439092
33,34,47.963907,1833.595362,0.801494,0.540234,0.439092,-0.095827,47.868080,0.028391,1833.623752,-0.003128,0.798365,0.540227,0.439100
34,35,47.868080,1833.623752,0.798365,0.540227,0.439100,-0.088571,47.779509,0.026535,1833.650287,-0.003025,0.795341,0.540222,0.439108
35,36,47.779509,1833.650287,0.795341,0.540222,0.439108,-0.081843,47.697666,0.024736,1833.675022,-0.002928,0.792413,0.540217,0.439115
36,37,47.697666,1833.675022,0.792413,0.540217,0.439115,-0.075692,47.621974,0.020567,1833.695589,-0.002838,0.789576,0.540212,0.439122
37,38,47.621974,1833.695589,0.789576,0.540212,0.439122,-0.069890,47.552085,0.007546,1833.703135,-0.002753,0.786823,0.540208,0.439128
38,39,47.552085,1833.703135,0.786823,0.540208,0.439128,-0.064491,47.487593,0.014344,1833.717479,-0.002673,0.784149,0.540204,0.439134
39,40,47.487593,1833.717479,0.784149,0.540204,0.439134,-0.059483,47.428110,0.016844,1833.734323,-0.002599,0.781550,0.540201,0.439140
40,41,47.428110,1833.734323,0.781550,0.540201,0.439140,-0.054549,47.373561,0.038132,1833.772455,-0.002527,0.779024,0.540198,0.439147
41,42,47.373561,1833.772455,0.779024,0.540198,0.439147,-0.050264,47.323297,0.040828,1833.813283,-0.002460,0.776563,0.540195,0.439153
42,43,47.323297,1833.813283,0.776563,0.540195,0.439153,-0.046283,47.277014,0.019719,1833.833001,-0.002398,0.774165,0.540192,0.439158
43,44,47.277014,1833.833001,0.774165,0.540192,0.439158,-0.042562,47.234453,0.013906,1833.846907,-0.002340,0.771825,0.540190,0.439163
44,45,47.234453,1833.846907,0.771825,0.540190,0.439163,-0.039095,47.195357,0.011679,1833.858586,-0.002284,0.769541,0.540188,0.439168
45,46,47.195357,1833.858586,0.769541,0.540188,0.439168,-0.035868,47.159490,0.010325,1833.868912,-0.002232,0.767309,0.540186,0.439173
46,47,47.159490,1833.868912,0.767309,0.540186,0.439173,-0.033022,47.126468,0.007411,1833.876322,-0.002183,0.765126,0.540184,0.439177
47,48,47.126468,1833.876322,0.765126,0.540184,0.439177,-0.030213,47.096255,-0.001152,1833.875170,-0.002136,0.762989,0.540182,0.439181
48,49,47.096255,1833.875170,0.762989,0.540182,0.439181,-0.027590,47.068665,-0.005089,1833.870081,-0.002092,0.760897,0.540180,0.439184
49,50,47.068665,1833.870081,0.760897,0.540180,0.439184,-0.025144,47.043521,-0.006835,1833.863246,-0.002050,0.758848,0.540179,0.439188